-- Time dimension and the product category hierarchy.

-- ---------------------------------------------------------------------------
-- dim_time
-- ---------------------------------------------------------------------------
-- Keyed on an integer YYYYMMDD surrogate rather than a SERIAL. The key is
-- derived from the date itself, so the ETL can compute it locally instead of
-- looking the row up, and reloading a day is naturally idempotent.
CREATE TABLE dim_time (
    date_key     INTEGER     PRIMARY KEY,           -- YYYYMMDD
    date         DATE        NOT NULL UNIQUE,
    day_of_week  SMALLINT    NOT NULL,              -- ISO: 1 = Monday .. 7 = Sunday
    day_name     VARCHAR(9)  NOT NULL,
    day_of_month SMALLINT    NOT NULL,
    day_of_year  SMALLINT    NOT NULL,
    week_of_year SMALLINT    NOT NULL,              -- ISO week
    month        SMALLINT    NOT NULL,
    month_name   VARCHAR(9)  NOT NULL,
    quarter      SMALLINT    NOT NULL,
    year         SMALLINT    NOT NULL,
    is_weekend   BOOLEAN     NOT NULL,
    is_holiday   BOOLEAN     NOT NULL,
    holiday_name VARCHAR(50)
);

COMMENT ON TABLE dim_time IS
    'Date dimension for time-based analysis. Populated by populate_dim_time().';

CREATE INDEX idx_dim_time_year_month ON dim_time (year, month);
CREATE INDEX idx_dim_time_date ON dim_time (date);

-- US federal holidays. Floating holidays are identified by weekday plus the
-- day-of-month window they can fall in (e.g. the 4th Thursday of November is
-- always between the 22nd and the 28th), which avoids any iterative search.
CREATE FUNCTION us_holiday_name(p_date DATE)
RETURNS VARCHAR(50)
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT CASE
        WHEN m = 1  AND d = 1                      THEN 'New Year''s Day'
        WHEN m = 1  AND dow = 1 AND d BETWEEN 15 AND 21 THEN 'Martin Luther King Jr. Day'
        WHEN m = 2  AND dow = 1 AND d BETWEEN 15 AND 21 THEN 'Presidents Day'
        WHEN m = 5  AND dow = 1 AND d BETWEEN 25 AND 31 THEN 'Memorial Day'
        WHEN m = 6  AND d = 19                     THEN 'Juneteenth'
        WHEN m = 7  AND d = 4                      THEN 'Independence Day'
        WHEN m = 9  AND dow = 1 AND d BETWEEN 1  AND 7  THEN 'Labor Day'
        WHEN m = 10 AND dow = 1 AND d BETWEEN 8  AND 14 THEN 'Columbus Day'
        WHEN m = 11 AND d = 11                     THEN 'Veterans Day'
        WHEN m = 11 AND dow = 4 AND d BETWEEN 22 AND 28 THEN 'Thanksgiving Day'
        WHEN m = 12 AND d = 25                     THEN 'Christmas Day'
        ELSE NULL
    END
    FROM (
        SELECT EXTRACT(MONTH  FROM p_date)::int AS m,
               EXTRACT(DAY    FROM p_date)::int AS d,
               EXTRACT(ISODOW FROM p_date)::int AS dow
    ) parts;
$$;

-- Fills dim_time for a date range. Idempotent: re-running over the same range
-- refreshes the rows rather than failing on the primary key.
CREATE FUNCTION populate_dim_time(p_start DATE, p_end DATE)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows INTEGER;
BEGIN
    IF p_end < p_start THEN
        RAISE EXCEPTION 'populate_dim_time: end date % precedes start date %', p_end, p_start;
    END IF;

    INSERT INTO dim_time (
        date_key, date, day_of_week, day_name, day_of_month, day_of_year,
        week_of_year, month, month_name, quarter, year, is_weekend,
        is_holiday, holiday_name
    )
    SELECT
        TO_CHAR(d, 'YYYYMMDD')::int,
        d::date,
        EXTRACT(ISODOW FROM d)::smallint,
        TRIM(TO_CHAR(d, 'Day')),
        EXTRACT(DAY FROM d)::smallint,
        EXTRACT(DOY FROM d)::smallint,
        EXTRACT(WEEK FROM d)::smallint,
        EXTRACT(MONTH FROM d)::smallint,
        TRIM(TO_CHAR(d, 'Month')),
        EXTRACT(QUARTER FROM d)::smallint,
        EXTRACT(YEAR FROM d)::smallint,
        EXTRACT(ISODOW FROM d) IN (6, 7),
        us_holiday_name(d::date) IS NOT NULL,
        us_holiday_name(d::date)
    FROM generate_series(p_start::timestamp, p_end::timestamp, INTERVAL '1 day') AS d
    ON CONFLICT (date_key) DO UPDATE SET
        is_holiday   = EXCLUDED.is_holiday,
        holiday_name = EXCLUDED.holiday_name;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN v_rows;
END;
$$;

-- Seed a range wide enough to cover the sample data and several years of
-- future loads. ~7,700 rows, so the storage cost is irrelevant.
SELECT populate_dim_time('2015-01-01'::date, '2035-12-31'::date);

-- ---------------------------------------------------------------------------
-- product_categories
-- ---------------------------------------------------------------------------
-- Self-referencing hierarchy: rows with parent_id IS NULL are top-level
-- categories, everything else is a subcategory.
CREATE TABLE product_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    parent_id   INTEGER      REFERENCES product_categories (category_id),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- A category cannot be its own parent. Deeper cycles are prevented by the
    -- ETL, which loads parents before children.
    CONSTRAINT chk_category_not_self_parent CHECK (parent_id IS DISTINCT FROM category_id)
);

CREATE INDEX idx_product_categories_parent_id ON product_categories (parent_id);
CREATE INDEX idx_product_categories_name ON product_categories (name);

-- Flattens the hierarchy so "top sellers by category" can roll a subcategory
-- up to its top-level ancestor without a recursive query per request.
CREATE VIEW category_hierarchy AS
WITH RECURSIVE tree AS (
    SELECT
        category_id,
        name,
        parent_id,
        category_id           AS root_category_id,
        name                  AS root_category_name,
        1                     AS depth,
        ARRAY[category_id]    AS path
    FROM product_categories
    WHERE parent_id IS NULL

    UNION ALL

    SELECT
        c.category_id,
        c.name,
        c.parent_id,
        t.root_category_id,
        t.root_category_name,
        t.depth + 1,
        t.path || c.category_id
    FROM product_categories c
    JOIN tree t ON c.parent_id = t.category_id
    -- Defensive bound: stops a data-entry cycle from spinning forever.
    WHERE NOT c.category_id = ANY (t.path)
)
SELECT category_id, name, parent_id, root_category_id, root_category_name, depth, path
FROM tree;

COMMENT ON VIEW category_hierarchy IS
    'Each category with its top-level ancestor and depth, for category rollups.';
