-- Products and customers: the two non-partitioned entity tables.

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    product_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)   NOT NULL,
    description     TEXT,
    price           NUMERIC(10, 2) NOT NULL,
    cost            NUMERIC(10, 2),
    category_id     INTEGER        NOT NULL REFERENCES product_categories (category_id),
    sku             VARCHAR(50)    NOT NULL UNIQUE,
    inventory_count INTEGER        NOT NULL DEFAULT 0,
    weight          NUMERIC(8, 2),
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

    -- Money and physical quantities are non-negative. These are cheap to
    -- enforce and turn a silent data-quality problem into a load failure.
    CONSTRAINT chk_products_price_non_negative     CHECK (price >= 0),
    CONSTRAINT chk_products_cost_non_negative      CHECK (cost IS NULL OR cost >= 0),
    CONSTRAINT chk_products_inventory_non_negative CHECK (inventory_count >= 0),
    CONSTRAINT chk_products_weight_non_negative    CHECK (weight IS NULL OR weight >= 0)
);

COMMENT ON TABLE products IS 'Product catalogue. SKU is the natural key used for ETL upserts.';

CREATE INDEX idx_products_category_id ON products (category_id);

-- Partial index: nearly every catalogue query filters on active products, so
-- indexing only those keeps the index roughly 90% of the table rather than
-- 100%, and makes the planner's job unambiguous.
CREATE INDEX idx_products_active_category ON products (category_id, product_id)
    WHERE is_active;

-- Trigram index backing case-insensitive substring search on product names.
CREATE INDEX idx_products_name_trgm ON products USING gin (name gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- customers
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    customer_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    first_name        VARCHAR(50)  NOT NULL,
    last_name         VARCHAR(50)  NOT NULL,
    street_address    VARCHAR(255),
    city              VARCHAR(100),
    state             VARCHAR(50),
    zip_code          VARCHAR(20),
    country           VARCHAR(50),
    phone             VARCHAR(50),
    registration_date TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    last_login        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Cheap structural check. Full validation belongs in the ETL, which
    -- quarantines bad rows instead of aborting the batch.
    CONSTRAINT chk_customers_email_shape CHECK (email LIKE '%_@_%.__%')
);

COMMENT ON TABLE customers IS
    'Customer master. Email is lower-cased by the ETL so the UNIQUE constraint '
    'behaves case-insensitively without needing citext.';

-- The reference schema declared both `email VARCHAR UNIQUE` and a separate
-- `idx_customers_email`. UNIQUE already builds a btree index, so the extra one
-- only cost write throughput and disk; it is not recreated here.
CREATE INDEX idx_customers_last_name ON customers (last_name);
CREATE INDEX idx_customers_location ON customers (country, state, city);
CREATE INDEX idx_customers_registration_date ON customers (registration_date);
