-- Orders, range-partitioned by month on order_date.
--
-- The reference schema declared `order_id SERIAL PRIMARY KEY` on a table
-- partitioned by order_date. PostgreSQL rejects that outright:
--
--   ERROR: unique constraint on partitioned table must include all
--          partitioning columns
--   DETAIL: PRIMARY KEY constraint on table "orders" lacks column "order_date"
--
-- The primary key is therefore (order_id, order_date). order_id remains unique
-- in practice because it comes from a single identity sequence; the composite
-- key exists to satisfy the partitioning rule and to give order_items a target
-- for its foreign key.

CREATE TABLE orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id      INTEGER        NOT NULL REFERENCES customers (customer_id),
    order_date       TIMESTAMPTZ    NOT NULL,
    status           order_status   NOT NULL DEFAULT 'Pending',
    payment_method   payment_method NOT NULL,
    shipping_address VARCHAR(255)   NOT NULL,
    shipping_city    VARCHAR(100)   NOT NULL,
    shipping_state   VARCHAR(50)    NOT NULL,
    shipping_zip     VARCHAR(20)    NOT NULL,
    shipping_country VARCHAR(50)    NOT NULL,
    processing_date  TIMESTAMPTZ,
    shipping_date    TIMESTAMPTZ,
    delivery_date    TIMESTAMPTZ,
    total_amount     NUMERIC(12, 2) NOT NULL,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_orders PRIMARY KEY (order_id, order_date),
    CONSTRAINT chk_orders_total_non_negative CHECK (total_amount >= 0),
    -- Fulfilment milestones must not run backwards.
    CONSTRAINT chk_orders_date_sequence CHECK (
        (processing_date IS NULL OR processing_date >= order_date)
        AND (shipping_date IS NULL OR processing_date IS NULL OR shipping_date >= processing_date)
        AND (delivery_date IS NULL OR shipping_date IS NULL OR delivery_date >= shipping_date)
    )
) PARTITION BY RANGE (order_date);

COMMENT ON TABLE orders IS
    'Orders, range-partitioned by month on order_date. Partitions are created '
    'by ensure_monthly_partitions(); orders_default catches out-of-range rows.';

-- ---------------------------------------------------------------------------
-- Partition management
-- ---------------------------------------------------------------------------
-- The reference schema hard-coded three monthly partitions (2023-01, 2023-02,
-- 2024-12) with a "... create more ..." comment in between, while the data
-- generator emits dates relative to now(). Almost every insert would have
-- failed with "no partition of relation ... found for row". Partitions are
-- generated here instead, and a DEFAULT partition backstops anything missed.

-- p_bound_suffix is appended to each YYYY-MM-DD boundary literal. For a
-- TIMESTAMPTZ partition key it carries an explicit UTC offset so the bounds do
-- not depend on the session TimeZone; for a DATE key the caller passes ''.
CREATE FUNCTION ensure_monthly_partitions(
    p_parent       TEXT,
    p_start        DATE,
    p_end          DATE,
    p_bound_suffix TEXT DEFAULT ' 00:00:00+00'
)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_month   DATE := date_trunc('month', p_start)::date;
    v_last    DATE := date_trunc('month', p_end)::date;
    v_name    TEXT;
    v_created INTEGER := 0;
BEGIN
    IF v_last < v_month THEN
        RAISE EXCEPTION 'ensure_monthly_partitions: end % precedes start %', p_end, p_start;
    END IF;

    WHILE v_month <= v_last LOOP
        v_name := format('%s_y%sm%s',
                         p_parent,
                         to_char(v_month, 'YYYY'),
                         to_char(v_month, 'MM'));

        IF to_regclass(quote_ident(v_name)) IS NULL THEN
            -- Bounds are written as explicit UTC literals so the partition
            -- boundaries do not depend on the session TimeZone setting.
            EXECUTE format(
                'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
                v_name,
                p_parent,
                to_char(v_month, 'YYYY-MM-DD') || p_bound_suffix,
                to_char(v_month + INTERVAL '1 month', 'YYYY-MM-DD') || p_bound_suffix
            );
            v_created := v_created + 1;
        END IF;

        v_month := (v_month + INTERVAL '1 month')::date;
    END LOOP;

    RETURN v_created;
END;
$$;

COMMENT ON FUNCTION ensure_monthly_partitions IS
    'Idempotently create monthly range partitions of p_parent covering '
    '[p_start, p_end]. Returns the number newly created.';

-- Lists partitions that are entirely older than a cutoff, so retention tooling
-- can DETACH and archive them. Dropping a partition is a metadata operation,
-- which is the main operational reason to partition this table at all.
CREATE FUNCTION orders_partitions_older_than(p_cutoff DATE)
RETURNS TABLE (partition_name TEXT, upper_bound TIMESTAMPTZ)
LANGUAGE sql
STABLE
AS $$
    SELECT
        c.relname::text,
        -- Parse the upper bound out of the stored partition expression.
        (regexp_match(
            pg_get_expr(c.relpartbound, c.oid),
            'TO \(''([^'']+)''\)'
        ))[1]::timestamptz
    FROM pg_class c
    JOIN pg_inherits i ON i.inhrelid = c.oid
    WHERE i.inhparent = 'orders'::regclass
      AND c.relpartbound IS NOT NULL
      AND pg_get_expr(c.relpartbound, c.oid) NOT LIKE '%DEFAULT%'
      AND (regexp_match(
            pg_get_expr(c.relpartbound, c.oid),
            'TO \(''([^'']+)''\)'
          ))[1]::timestamptz <= p_cutoff
    ORDER BY 2;
$$;

-- Cover the sample data and a few years either side. The ETL calls
-- ensure_monthly_partitions() for the range it is about to load, so ongoing
-- operation does not depend on this seed range.
SELECT ensure_monthly_partitions('orders', '2019-01-01'::date, '2030-12-31'::date);

-- Safety net for rows outside every declared range. It should stay empty; the
-- data-quality checks in 009 fail the run when it is not, so a missing
-- partition surfaces as an alert instead of silent data loss.
CREATE TABLE orders_default PARTITION OF orders DEFAULT;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
-- Declared on the parent, so PostgreSQL creates and attaches a matching index
-- on every existing and future partition automatically.

-- Customer purchase history: equality on customer, newest orders first.
CREATE INDEX idx_orders_customer_date ON orders (customer_id, order_date DESC);

-- BRIN rather than btree on order_date: within a monthly partition the rows are
-- physically near-ordered by date because the ETL loads chronologically, so a
-- BRIN summarises the whole partition in a few KB. Partition pruning already
-- handles month-level filtering; this covers narrower ranges inside a month.
CREATE INDEX idx_orders_date_brin ON orders USING brin (order_date)
    WITH (pages_per_range = 32);

-- Status is low cardinality on its own, so it is only worth indexing in
-- combination with the date range that every analytics query also applies.
CREATE INDEX idx_orders_status_date ON orders (status, order_date);
