-- Order line items, partitioned identically to orders.
--
-- The reference schema commented that this table was "partitioned by order_date
-- as well for consistent joins", but declared no PARTITION BY and carried no
-- order_date column, and dropped the foreign key with the note that partitioned
-- tables cannot be referenced. That has not been true since PostgreSQL 12.
--
-- order_date is denormalised onto the line item for two reasons: it lets this
-- table use the same monthly range partitioning as its parent (so joins are
-- partition-wise), and it supplies the second half of the composite key needed
-- to reference orders (order_id, order_date).

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id      BIGINT         NOT NULL,
    order_date    TIMESTAMPTZ    NOT NULL,
    product_id    INTEGER        NOT NULL REFERENCES products (product_id),
    quantity      INTEGER        NOT NULL,
    unit_price    NUMERIC(10, 2) NOT NULL,
    discount      NUMERIC(10, 2) NOT NULL DEFAULT 0,

    -- Business rule "revenue = price x quantity - discount" implemented as a
    -- stored generated column. Computing it in the database rather than the
    -- ETL means the value cannot drift from its inputs, no matter which writer
    -- touches the row. The ETL still cross-checks it against the source file's
    -- own total as a data-quality signal.
    line_revenue  NUMERIC(12, 2)
        GENERATED ALWAYS AS (unit_price * quantity - discount) STORED,

    created_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_order_items PRIMARY KEY (order_item_id, order_date),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id, order_date) REFERENCES orders (order_id, order_date)
        ON DELETE CASCADE,
    CONSTRAINT chk_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_order_items_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT chk_order_items_discount_valid
        CHECK (discount >= 0 AND discount <= unit_price * quantity)
) PARTITION BY RANGE (order_date);

COMMENT ON TABLE order_items IS
    'Order line items. Partitioned by order_date to match orders, enabling '
    'partition-wise joins and aligned retention.';

COMMENT ON COLUMN order_items.line_revenue IS
    'Generated: unit_price * quantity - discount.';

SELECT ensure_monthly_partitions('order_items', '2019-01-01'::date, '2030-12-31'::date);

CREATE TABLE order_items_default PARTITION OF order_items DEFAULT;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Joining back to orders, and the ON DELETE CASCADE, both drive lookups by
-- (order_id, order_date).
CREATE INDEX idx_order_items_order ON order_items (order_id, order_date);

-- Top-selling products over a period. The INCLUDE columns carry the two
-- measures the aggregate needs, so the query can be satisfied by an index-only
-- scan without visiting the heap.
CREATE INDEX idx_order_items_product_date ON order_items (product_id, order_date)
    INCLUDE (quantity, line_revenue);

CREATE INDEX idx_order_items_date_brin ON order_items USING brin (order_date)
    WITH (pages_per_range = 32);
