-- ETL bookkeeping: run history, incremental watermarks, data-quality results,
-- and the helpers the loader needs after a bulk COPY.

-- Every timestamp in this schema is TIMESTAMPTZ and every partition bound is a
-- UTC literal, so pin the database timezone rather than inheriting the host's.
-- Takes effect for sessions opened after this migration.
DO $$
BEGIN
    EXECUTE format('ALTER DATABASE %I SET timezone TO %L', current_database(), 'UTC');
END;
$$;

CREATE TYPE etl_run_status AS ENUM ('running', 'succeeded', 'failed');
CREATE TYPE dq_severity AS ENUM ('warning', 'error');

-- ---------------------------------------------------------------------------
-- etl_run
-- ---------------------------------------------------------------------------
CREATE TABLE etl_run (
    run_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow       VARCHAR(100)   NOT NULL,
    source         TEXT,
    status         etl_run_status NOT NULL DEFAULT 'running',
    started_at     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    finished_at    TIMESTAMPTZ,
    rows_extracted BIGINT         NOT NULL DEFAULT 0,
    rows_loaded    BIGINT         NOT NULL DEFAULT 0,
    rows_rejected  BIGINT         NOT NULL DEFAULT 0,
    error_message  TEXT,

    CONSTRAINT chk_etl_run_finished CHECK (
        (status = 'running' AND finished_at IS NULL)
        OR (status <> 'running' AND finished_at IS NOT NULL)
    )
);

COMMENT ON TABLE etl_run IS
    'One row per pipeline execution. Gives Flyte and operators a queryable '
    'history independent of container logs.';

CREATE INDEX idx_etl_run_workflow_started ON etl_run (workflow, started_at DESC);
CREATE INDEX idx_etl_run_status ON etl_run (status) WHERE status <> 'succeeded';

-- ---------------------------------------------------------------------------
-- etl_watermark
-- ---------------------------------------------------------------------------
-- Drives incremental loads: each entity records the high-water mark of the
-- data already ingested, so the next run only reads rows beyond it.
CREATE TABLE etl_watermark (
    entity       VARCHAR(100) PRIMARY KEY,
    watermark_ts TIMESTAMPTZ,
    watermark_id BIGINT,
    last_run_id  BIGINT REFERENCES etl_run (run_id),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE etl_watermark IS
    'High-water mark per entity for incremental extraction.';

-- Advances a watermark only when the new value is actually later, so an
-- out-of-order or replayed batch cannot move it backwards.
CREATE FUNCTION advance_watermark(
    p_entity VARCHAR(100),
    p_ts     TIMESTAMPTZ,
    p_run_id BIGINT DEFAULT NULL
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
AS $$
DECLARE
    v_current TIMESTAMPTZ;
BEGIN
    INSERT INTO etl_watermark (entity, watermark_ts, last_run_id, updated_at)
    VALUES (p_entity, p_ts, p_run_id, NOW())
    ON CONFLICT (entity) DO UPDATE SET
        watermark_ts = GREATEST(etl_watermark.watermark_ts, EXCLUDED.watermark_ts),
        last_run_id  = EXCLUDED.last_run_id,
        updated_at   = NOW()
    RETURNING watermark_ts INTO v_current;

    RETURN v_current;
END;
$$;

-- ---------------------------------------------------------------------------
-- data_quality_check
-- ---------------------------------------------------------------------------
CREATE TABLE data_quality_check (
    check_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      BIGINT       REFERENCES etl_run (run_id) ON DELETE CASCADE,
    check_name  VARCHAR(100) NOT NULL,
    severity    dq_severity  NOT NULL DEFAULT 'error',
    passed      BOOLEAN      NOT NULL,
    observed    NUMERIC,
    threshold   NUMERIC,
    details     TEXT,
    checked_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dq_run ON data_quality_check (run_id, checked_at);
CREATE INDEX idx_dq_failures ON data_quality_check (check_name, checked_at DESC)
    WHERE NOT passed;

-- ---------------------------------------------------------------------------
-- Post-load helpers
-- ---------------------------------------------------------------------------

-- Bulk loads COPY explicit primary keys straight from the source files, which
-- never advances the identity sequences behind those columns. Left unfixed,
-- the first row inserted afterwards without an explicit id collides with an
-- existing key. Called by the ETL at the end of every load.
CREATE FUNCTION sync_identity_sequences()
RETURNS TABLE (table_name TEXT, column_name TEXT, next_value BIGINT)
LANGUAGE plpgsql
AS $$
DECLARE
    r        RECORD;
    v_seq    TEXT;
    v_max    BIGINT;
BEGIN
    FOR r IN
        SELECT c.table_name AS tbl, c.column_name AS col
        FROM information_schema.columns c
        JOIN information_schema.tables t
          ON t.table_schema = c.table_schema AND t.table_name = c.table_name
        WHERE c.table_schema = 'public'
          AND c.is_identity = 'YES'
          AND t.table_type IN ('BASE TABLE', 'FOREIGN')
        ORDER BY c.table_name
    LOOP
        v_seq := pg_get_serial_sequence(format('public.%I', r.tbl), r.col);
        CONTINUE WHEN v_seq IS NULL;

        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM public.%I', r.col, r.tbl)
        INTO v_max;

        -- is_called = false means the *next* nextval() returns v_max + 1.
        PERFORM setval(v_seq, v_max + 1, false);

        table_name  := r.tbl;
        column_name := r.col;
        next_value  := v_max + 1;
        RETURN NEXT;
    END LOOP;
END;
$$;

-- Counts rows that landed in a DEFAULT partition. Any non-zero result means a
-- range partition was missing when the data arrived: the rows are safe, but
-- they are not pruned or aligned, so the ETL treats this as a failing check.
CREATE FUNCTION count_default_partition_rows()
RETURNS TABLE (partition_name TEXT, row_count BIGINT)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    r     RECORD;
    v_cnt BIGINT;
BEGIN
    FOR r IN
        SELECT c.relname::text AS relname
        FROM pg_class c
        JOIN pg_inherits i ON i.inhrelid = c.oid
        WHERE c.relpartbound IS NOT NULL
          AND pg_get_expr(c.relpartbound, c.oid) = 'DEFAULT'
        ORDER BY c.relname
    LOOP
        EXECUTE format('SELECT COUNT(*) FROM public.%I', r.relname) INTO v_cnt;
        partition_name := r.relname;
        row_count      := v_cnt;
        RETURN NEXT;
    END LOOP;
END;
$$;
