"""GraphQL type definitions."""

from __future__ import annotations

import enum
from datetime import date, datetime
from decimal import Decimal
from typing import Any

import strawberry


# ---------------------------------------------------------------------------
# enums
# ---------------------------------------------------------------------------


@strawberry.enum
class ProductSalesSort(enum.Enum):
    REVENUE = "REVENUE"
    UNITS = "UNITS"
    ORDERS = "ORDERS"
    NAME = "NAME"


@strawberry.enum
class ProductSort(enum.Enum):
    NAME = "NAME"
    PRICE = "PRICE"
    CREATED_AT = "CREATED_AT"
    INVENTORY = "INVENTORY"


@strawberry.enum
class CustomerSort(enum.Enum):
    LIFETIME_VALUE = "LIFETIME_VALUE"
    ORDER_COUNT = "ORDER_COUNT"
    LAST_ORDER = "LAST_ORDER"
    NAME = "NAME"


@strawberry.enum
class Granularity(enum.Enum):
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    QUARTER = "QUARTER"
    YEAR = "YEAR"


@strawberry.enum
class OrderStatus(enum.Enum):
    PENDING = "Pending"
    PROCESSING = "Processing"
    SHIPPED = "Shipped"
    IN_TRANSIT = "In Transit"
    DELIVERED = "Delivered"
    CANCELLED = "Cancelled"
    RETURNED = "Returned"


# ---------------------------------------------------------------------------
# inputs
# ---------------------------------------------------------------------------


@strawberry.input
class DateRange:
    """Inclusive at both ends."""

    from_date: date
    to_date: date


@strawberry.input
class PageInput:
    limit: int = 50
    offset: int = 0


@strawberry.input
class ProductFilter:
    search: str | None = None
    category_id: int | None = None
    active_only: bool = False
    min_price: float | None = None
    max_price: float | None = None


@strawberry.input
class CustomerFilter:
    search: str | None = None
    country: str | None = None
    min_lifetime_value: float | None = None


@strawberry.input
class UpdateProductInput:
    """Partial update: omitted fields are left untouched."""

    name: str | None = None
    description: str | None = None
    price: Decimal | None = None
    cost: Decimal | None = None
    category_id: int | None = None
    sku: str | None = None
    inventory_count: int | None = None
    weight: Decimal | None = None
    is_active: bool | None = None


# ---------------------------------------------------------------------------
# object types
# ---------------------------------------------------------------------------


@strawberry.type
class Category:
    category_id: int
    name: str
    description: str | None
    parent_id: int | None

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> Category:
        return cls(
            category_id=row["category_id"],
            name=row["name"],
            description=row.get("description"),
            parent_id=row.get("parent_id"),
        )


@strawberry.type
class Product:
    product_id: int
    name: str
    description: str | None
    price: Decimal
    cost: Decimal | None
    sku: str
    inventory_count: int
    weight: Decimal | None
    is_active: bool
    created_at: datetime
    updated_at: datetime

    # Kept private so `category` can be resolved through a DataLoader instead
    # of being fetched eagerly for every product in a page.
    category_id: strawberry.Private[int]

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> Product:
        return cls(
            product_id=row["product_id"],
            name=row["name"],
            description=row.get("description"),
            price=row["price"],
            cost=row.get("cost"),
            sku=row["sku"],
            inventory_count=row["inventory_count"],
            weight=row.get("weight"),
            is_active=row["is_active"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            category_id=row["category_id"],
        )

    @strawberry.field(description="Batched through a DataLoader.")
    async def category(self, info: strawberry.Info) -> Category | None:
        row = await info.context["loaders"].category.load(self.category_id)
        return Category.from_row(row) if row else None


@strawberry.type
class OrderItem:
    order_item_id: int
    order_id: int
    quantity: int
    unit_price: Decimal
    discount: Decimal
    line_revenue: Decimal = strawberry.field(
        description="Generated by the database as unit_price * quantity - discount."
    )

    product_id: strawberry.Private[int]

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> OrderItem:
        return cls(
            order_item_id=row["order_item_id"],
            order_id=row["order_id"],
            quantity=row["quantity"],
            unit_price=row["unit_price"],
            discount=row["discount"],
            line_revenue=row["line_revenue"],
            product_id=row["product_id"],
        )

    @strawberry.field(description="Batched through a DataLoader.")
    async def product(self, info: strawberry.Info) -> Product | None:
        row = await info.context["loaders"].product.load(self.product_id)
        return Product.from_row(row) if row else None


@strawberry.type
class Order:
    order_id: int
    order_date: datetime
    status: str
    payment_method: str
    shipping_city: str
    shipping_state: str
    shipping_country: str
    processing_date: datetime | None
    shipping_date: datetime | None
    delivery_date: datetime | None
    total_amount: Decimal

    customer_id: strawberry.Private[int]

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> Order:
        return cls(
            order_id=row["order_id"],
            order_date=row["order_date"],
            status=row["status"],
            payment_method=row["payment_method"],
            shipping_city=row["shipping_city"],
            shipping_state=row["shipping_state"],
            shipping_country=row["shipping_country"],
            processing_date=row.get("processing_date"),
            shipping_date=row.get("shipping_date"),
            delivery_date=row.get("delivery_date"),
            total_amount=row["total_amount"],
            customer_id=row["customer_id"],
        )

    @strawberry.field(description="Line items, batched by (order_id, order_date).")
    async def items(self, info: strawberry.Info) -> list[OrderItem]:
        rows = await info.context["loaders"].order_items.load(
            (self.order_id, self.order_date)
        )
        return [OrderItem.from_row(row) for row in rows]

    @strawberry.field(description="Batched through a DataLoader.")
    async def customer(self, info: strawberry.Info) -> Customer | None:
        row = await info.context["loaders"].customer.load(self.customer_id)
        return Customer.from_row(row) if row else None


@strawberry.type
class Customer:
    customer_id: int
    email: str
    first_name: str
    last_name: str
    city: str | None
    state: str | None
    country: str | None
    registration_date: datetime
    order_count: int
    lifetime_value: Decimal
    avg_order_value: Decimal
    first_order_date: datetime | None
    last_order_date: datetime | None
    avg_days_between_orders: Decimal | None = strawberry.field(
        description="Mean gap between consecutive orders; null for a single order."
    )

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> Customer:
        return cls(
            customer_id=row["customer_id"],
            email=row["email"],
            first_name=row["first_name"],
            last_name=row["last_name"],
            city=row.get("city"),
            state=row.get("state"),
            country=row.get("country"),
            registration_date=row["registration_date"],
            order_count=row.get("order_count") or 0,
            lifetime_value=row.get("lifetime_value") or 0,
            avg_order_value=row.get("avg_order_value") or 0,
            first_order_date=row.get("first_order_date"),
            last_order_date=row.get("last_order_date"),
            avg_days_between_orders=row.get("avg_days_between_orders"),
        )


@strawberry.type
class ProductSales:
    """A product's aggregated sales over the requested period."""

    product_id: int
    product_name: str
    sku: str
    category_id: int
    category_name: str
    units_sold: int
    net_revenue: Decimal
    gross_revenue: Decimal
    discount_total: Decimal
    order_count: int

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> ProductSales:
        return cls(
            product_id=row["product_id"],
            product_name=row["product_name"],
            sku=row["sku"],
            category_id=row["category_id"],
            category_name=row["category_name"],
            units_sold=int(row["units_sold"] or 0),
            net_revenue=row["net_revenue"] or 0,
            gross_revenue=row["gross_revenue"] or 0,
            discount_total=row["discount_total"] or 0,
            order_count=int(row["order_count"] or 0),
        )

    @strawberry.field(description="Batched through a DataLoader.")
    async def product(self, info: strawberry.Info) -> Product | None:
        row = await info.context["loaders"].product.load(self.product_id)
        return Product.from_row(row) if row else None


@strawberry.type
class RankedProduct:
    """A product's position within its category for the period."""

    rank: int
    category_id: int
    category_name: str
    product_id: int
    product_name: str
    sku: str
    units_sold: int
    net_revenue: Decimal
    order_count: int

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> RankedProduct:
        return cls(
            rank=int(row["rank"]),
            category_id=row["category_id"],
            category_name=row["category_name"],
            product_id=row["product_id"],
            product_name=row["product_name"],
            sku=row["sku"],
            units_sold=int(row["units_sold"] or 0),
            net_revenue=row["net_revenue"] or 0,
            order_count=int(row["order_count"] or 0),
        )


@strawberry.type
class TrendPoint:
    bucket_start: date
    units_sold: int
    net_revenue: Decimal
    gross_revenue: Decimal
    discount_total: Decimal
    order_count: int
    distinct_products: int

    @classmethod
    def from_row(cls, row: dict[str, Any]) -> TrendPoint:
        return cls(
            bucket_start=row["bucket_start"],
            units_sold=int(row["units_sold"] or 0),
            net_revenue=row["net_revenue"] or 0,
            gross_revenue=row["gross_revenue"] or 0,
            discount_total=row["discount_total"] or 0,
            order_count=int(row["order_count"] or 0),
            distinct_products=int(row["distinct_products"] or 0),
        )


# ---------------------------------------------------------------------------
# pagination wrappers
# ---------------------------------------------------------------------------


@strawberry.type
class PageInfo:
    total_count: int
    has_next_page: bool
    limit: int
    offset: int


@strawberry.type
class ProductSalesPage:
    items: list[ProductSales]
    page_info: PageInfo


@strawberry.type
class ProductPage:
    items: list[Product]
    page_info: PageInfo


@strawberry.type
class CustomerPage:
    items: list[Customer]
    page_info: PageInfo


@strawberry.type
class OrderCursorPage:
    """Keyset-paginated orders.

    `endCursor` encodes (order_date, order_id); pass it back as `after` to get
    the next page. Keyset rather than offset because a purchase history is
    unbounded and OFFSET makes the database walk every skipped row.
    """

    items: list[Order]
    has_next_page: bool
    end_cursor: str | None


@strawberry.type
class UpdateProductResult:
    product: Product | None
    success: bool
    message: str
